### ISSUE TITLE
Selected text

### ISSUE THREAD

**Issue by thorstenkampe** [liuhewei/run-app-sublime#2]
It would be great to be able to pass selected text (or text under the cursor) to the application run. This would be an enhancement.

**Comment by liuhewei** [comment]
What you said is a good feature. Maybe I can add one more command to do this, but I'm afraid I don't have enough time recently for implement this. I will think about it later or you can give one PR if possible :)

**Comment by liuhewei** [comment]
now support send current selected text as the input https://github.com/liuhewei/run-app-sublime/commit/488ed52b71e9948ad75c52733b977d2dfb3d7745
