### ISSUE TITLE
DOS Prompt?

### ISSUE THREAD

**Issue by GaryFurash** [liuhewei/run-app-sublime#5]
```
{
    "caption": "Run: Explorer",
    "command": "runapp",
    "args":{
        "app": "C:\\Windows\\explorer.exe",
        "args": [""],
        "type": "dir"
    }
}
```

opens up windows explorer, but

```
{
    "caption": "Run: DOS",
    "command": "runapp",
    "args":{
        "app": "C:\\WINDOWS\\SYSWOW64\\CMD.EXE",
        "args": ["/K"],
        "type": "none"
    }
}
```

doesn't do anything.

**Comment by liuhewei** [comment]
When you use "Run: xxx", the real action is just the same as: Run the executive file in CMD environment.

So, your "Run: DOS" is the same as: Open CMD window, input `C:\WINDOWS\SYSWOW64\CMD.EXE` and press enter. I didn't capture the output of the command in "Run Apps", so there is nothing.

**Comment by liuhewei** [comment]
The new version provides the error message and output of app correctly.
